the config files to setup pyenv locally and globally were added
UjjwalBudha/ansible_pyenv_local_global pull request #1
Opened 2024-05-27 05:50 UTC by UjjwalBudha

I have uploaded the code for setting up pyenv and installing pyenv locally and globally using Ansible as well as i have added terraform config files for creating a ec2 instance.

2024-05-27 07:25 UTC, milandangol requested changes

2024-05-27 07:25 UTC, milandangol commented on ansible/roles/pyenv/tasks/main.yml
> +- name: Install pyenv dependencies
Lets use variable and for loop concept for this

2024-05-27 07:25 UTC, milandangol commented on ansible/roles/pyenv/tasks/main.yml
> +- name: Execute pyenv install script
lets not use shell  module for this. Please use script module

2024-05-27 07:25 UTC, milandangol commented on ansible/roles/pyenv/tasks/main.yml
> +# - name:
if not needed lets delet it

2024-05-27 07:25 UTC, milandangol commented on ansible/roles/pyenv/tasks/main.yml
> +- name: Check if Python 3.10.4 is already installed
lets not hardcode versions like this use variable

2024-05-27 07:34 UTC, UjjwalBudha commented on ansible/roles/pyenv/tasks/main.yml
> +# - name:
deleted the commented block of the code

2024-05-27 11:34 UTC, UjjwalBudha commented on ansible/roles/pyenv/tasks/main.yml
> +- name: Execute pyenv install script
included script module to execute pyenv script

2024-05-27 11:35 UTC, UjjwalBudha commented on ansible/roles/pyenv/tasks/main.yml
> +- name: Check if Python 3.10.4 is already installed
created separate variables for the different versions

2024-05-27 11:36 UTC, UjjwalBudha commented on ansible/roles/pyenv/tasks/main.yml
> +- name: Install pyenv dependencies
used variables to install all required dependencies

2024-05-28 05:02 UTC, milandangol approved these changes

2024-05-29 07:23 UTC, merged